# Shell variables
# Generated by 'wal'
wallpaper='/home/jedediah/Pictures/Wallpaper/forest_minimal.jpg'

# Special
background='#0D1D23'
foreground='#dceabf'
cursor='#dceabf'

# Colors
color0='#0D1D23'
color1='#3F8C61'
color2='#54986D'
color3='#5CA174'
color4='#90BA7A'
color5='#77B188'
color6='#A7CD87'
color7='#dceabf'
color8='#9aa385'
color9='#3F8C61'
color10='#54986D'
color11='#5CA174'
color12='#90BA7A'
color13='#77B188'
color14='#A7CD87'
color15='#dceabf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
