--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jedediah/Pictures/Wallpapers/lookout.jpg"

-- Special
background="#0A1E20"
foreground="#ddeabf"
cursor="#ddeabf"

-- Colors
color0="#0A1E20"
color1="#3E8E62"
color2="#54986D"
color3="#5CA175"
color4="#8EB777"
color5="#77B188"
color6="#A7CE8A"
color7="#ddeabf"
color8="#9aa385"
color9="#3E8E62"
color10="#54986D"
color11="#5CA175"
color12="#8EB777"
color13="#77B188"
color14="#A7CE8A"
color15="#ddeabf"
