--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jedediah/Pictures/Wallpaper/forest_minimal.jpg"

-- Special
background="#0D1D23"
foreground="#dceabf"
cursor="#dceabf"

-- Colors
color0="#0D1D23"
color1="#3F8C61"
color2="#54986D"
color3="#5CA174"
color4="#90BA7A"
color5="#77B188"
color6="#A7CD87"
color7="#dceabf"
color8="#9aa385"
color9="#3F8C61"
color10="#54986D"
color11="#5CA174"
color12="#90BA7A"
color13="#77B188"
color14="#A7CD87"
color15="#dceabf"
